FROM php:8.4-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git \
    curl \ 
    libpng-dev \ 
    libonig-dev \
    libxml2-dev \ 
    zip \ 
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . . 

RUN chown -R www-data:www-data /var/www \ 
    && chmod -R 755 /var/www

EXPOSE 9000

CMD ["php-fpm"]